name: Exectution Code
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is step 1 which will succeed"
      - name: Step 2
        run: echo "This is step 2 which will fail" && exit 1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "This is step 1 of job 2"
      - name: Step 2
        run: echo "This is step 2 of job 2"
