name: 12 - Outputs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.set_output.outputs.build_version }}
    steps:
      - name: Set Build Version
        id: set_output
        run: |
          echo "build_version=2.1.0" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying version ${{ needs.build.outputs.build_version }}"
