name: 14 Composit Actions
on:
  workflow_dispatch:
    inputs:
      name:
        description: "The name to use."
        required: true
        default: "Toby"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node and NPM Dependencies
        uses: "./.github/actions/js-deps-update"
        with:
          name: ${{ inputs.name }}
