name: 15 Custom Actions
on:
  workflow_dispatch:
    inputs:
      name:
        description: "The name to use."
        required: true
        default: "Toby"

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node and NPM Dependencies
        uses: "./.github/actions/composite_cache_deps"
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
